-- ============================================================================
-- INSERT COURSESKILLS DATA FROM course_skills.csv
-- Maps skills to courses based on CSV data
-- ============================================================================

-- ============================================================================
-- NOTE: This script inserts data from course_skills.csv
-- Format: course_id, skill_name
-- Total records: 2,000 unique course-skill mappings
-- ============================================================================

INSERT INTO [dbo].[CourseSkill] (
    [CourseId],
    [SkillId],
    [IsRequired],
    [ProficiencyLevel],
    [CreatedAt]
) SELECT
    cs.[course_id] AS [CourseId],
    s.[SkillId],
    1 AS [IsRequired],  -- All skills from CSV are considered required
    'Proficient' AS [ProficiencyLevel],  -- Default proficiency level
    GETDATE() AS [CreatedAt]
FROM (
    -- CSV Data inline
    VALUES
    (41,'TypeScript'),
    (23,'SQL Database'),
    (6,'Linux'),
    (46,'Git'),
    (26,'JavaScript'),
    (28,'Algorithms'),
    (11,'Web Security'),
    (41,'CI/CD'),
    (50,'REST APIs'),
    (31,'HTML/CSS'),
    (49,'AWS'),
    (17,'Git'),
    (11,'Data Structures'),
    (36,'React'),
    (23,'Python Programming'),
    (43,'AWS'),
    (6,'C#'),
    (15,'Data Structures'),
    (29,'.NET'),
    (37,'GraphQL'),
    (21,'AWS'),
    (27,'Testing'),
    (18,'Vue.js'),
    (38,'DevOps'),
    (24,'Java'),
    (22,'MongoDB'),
    (46,'REST APIs'),
    (42,'MongoDB'),
    (28,'Git'),
    (25,'JavaScript'),
    (25,'Flask'),
    (39,'System Design'),
    (3,'Node.js'),
    (5,'Angular'),
    (47,'JavaScript'),
    (26,'Testing'),
    (8,'Python Programming'),
    (10,'Python Programming'),
    (20,'Git'),
    (27,'MongoDB'),
    (28,'HTML/CSS'),
    (25,'SQL Database'),
    (11,'Algorithms'),
    (39,'MongoDB'),
    (12,'MongoDB'),
    (33,'AWS'),
    (23,'Data Structures'),
    (7,'TypeScript'),
    (51,'Linux'),
    (43,'System Design'),
    (50,'GraphQL'),
    (20,'React'),
    (26,'Node.js'),
    (31,'Django'),
    (4,'.NET'),
    (25,'Testing'),
    (4,'Git'),
    (47,'Angular'),
    (26,'HTML/CSS'),
    (28,'GraphQL'),
    (23,'Testing'),
    (26,'Git'),
    (46,'DevOps'),
    (48,'SQL Database'),
    (37,'Node.js'),
    (23,'Linux'),
    (13,'GraphQL'),
    (21,'Java'),
    (23,'Flask'),
    (31,'System Design'),
    (43,'Vue.js'),
    (24,'MongoDB'),
    (31,'GraphQL'),
    (24,'Git'),
    (21,'Algorithms'),
    (4,'Docker'),
    (26,'Java'),
    (35,'Testing'),
    (16,'CI/CD'),
    (40,'C#'),
    (33,'Node.js'),
    (37,'Azure'),
    (50,'Java'),
    (9,'DevOps'),
    (45,'.NET'),
    (26,'GraphQL'),
    (43,'React'),
    (16,'DevOps'),
    (12,'Web Security'),
    (45,'Django'),
    (26,'Python Programming'),
    (49,'Algorithms'),
    (27,'Java'),
    (36,'JavaScript'),
    (16,'SQL Database'),
    (21,'JavaScript'),
    (19,'Flask'),
    (8,'React'),
    (5,'Java'),
    (29,'Git'),
    (42,'Flask'),
    (37,'React'),
    (37,'Flask'),
    (15,'TypeScript'),
    (47,'Flask'),
    (11,'.NET'),
    (22,'C#'),
    (48,'AWS'),
    (33,'React'),
    (10,'SQL Database'),
    (44,'React'),
    (19,'SQL Database'),
    (30,'AWS'),
    (25,'React'),
    (27,'Angular'),
    (13,'Flask'),
    (29,'Node.js'),
    (31,'REST APIs'),
    (38,'AWS'),
    (2,'React'),
    (11,'REST APIs'),
    (2,'Angular'),
    (39,'REST APIs'),
    (22,'Web Security'),
    (28,'SQL Database'),
    (20,'Data Structures'),
    (50,'Docker'),
    (51,'Node.js'),
    (14,'Git'),
    (10,'TypeScript'),
    (5,'Data Structures'),
    (7,'Node.js'),
    (48,'DevOps'),
    (5,'DevOps'),
    (12,'REST APIs'),
    (38,'Node.js'),
    (8,'C#'),
    (5,'REST APIs'),
    (9,'.NET'),
    (8,'TypeScript'),
    (6,'HTML/CSS'),
    (16,'TypeScript'),
    (38,'Angular'),
    (27,'TypeScript'),
    (19,'Node.js'),
    (36,'DevOps'),
    (31,'Testing'),
    (31,'Python Programming'),
    (13,'Testing'),
    (38,'Web Security'),
    (49,'.NET'),
    (15,'Git'),
    (51,'AWS'),
    (7,'Kubernetes'),
    (50,'CI/CD'),
    (17,'REST APIs'),
    (9,'SQL Database'),
    (49,'Web Security'),
    (23,'JavaScript'),
    (28,'.NET'),
    (44,'Java'),
    (14,'TypeScript'),
    (8,'DevOps'),
    (30,'SQL Database'),
    (19,'Data Structures'),
    (44,'SQL Database'),
    (30,'DevOps'),
    (17,'System Design'),
    (6,'Algorithms'),
    (7,'MongoDB'),
    (27,'CI/CD'),
    (17,'JavaScript'),
    (17,'C#'),
    (22,'AWS'),
    (28,'Kubernetes'),
    (11,'Node.js'),
    (48,'GraphQL'),
    (34,'MongoDB'),
    (37,'SQL Database'),
    (10,'React'),
    (18,'Kubernetes'),
    (50,'Kubernetes'),
    (47,'CI/CD'),
    (49,'TypeScript'),
    (24,'Testing'),
    (44,'Testing'),
    (38,'Git'),
    (46,'C#'),
    (8,'Kubernetes'),
    (42,'Web Security'),
    (10,'GraphQL'),
    (19,'Algorithms'),
    (42,'SQL Database'),
    (34,'Java'),
    (23,'GraphQL'),
    (16,'Web Security'),
    (18,'Git'),
    (38,'Django'),
    (43,'Azure'),
    (29,'MongoDB'),
    (27,'Git'),
    (30,'Vue.js'),
    (8,'Web Security'),
    (19,'DevOps'),
    (31,'Docker'),
    (23,'TypeScript'),
    (37,'Algorithms'),
    (16,'C#'),
    (4,'Angular'),
    (9,'JavaScript'),
    (18,'AWS'),
    (14,'Node.js'),
    (21,'CI/CD'),
    (40,'SQL Database'),
    (28,'Data Structures'),
    (29,'Testing'),
    (3,'AWS'),
    (44,'Node.js'),
    (7,'SQL Database'),
    (13,'Data Structures'),
    (12,'Java'),
    (30,'Azure'),
    (16,'Git'),
    (11,'Django'),
    (27,'React'),
    (34,'Angular'),
    (27,'Azure'),
    (45,'Kubernetes'),
    (11,'Git'),
    (5,'Vue.js'),
    (19,'C#'),
    (9,'System Design'),
    (3,'Flask'),
    (6,'Vue.js'),
    (38,'CI/CD'),
    (9,'Kubernetes'),
    (42,'Node.js'),
    (46,'CI/CD'),
    (42,'Django'),
    (29,'JavaScript'),
    (37,'TypeScript'),
    (8,'MongoDB'),
    (18,'React'),
    (14,'.NET'),
    (11,'MongoDB'),
    (20,'Algorithms'),
    (16,'Kubernetes'),
    (45,'HTML/CSS'),
    (28,'Azure'),
    (38,'Linux'),
    (29,'Vue.js'),
    (25,'Web Security'),
    (50,'Azure'),
    (32,'Kubernetes'),
    (23,'.NET'),
    (13,'Vue.js'),
    (44,'REST APIs'),
    (29,'REST APIs'),
    (19,'Vue.js'),
    (23,'Azure'),
    (36,'MongoDB'),
    (4,'DevOps'),
    (14,'Kubernetes'),
    (3,'Web Security'),
    (38,'Docker'),
    (51,'GraphQL'),
    (48,'TypeScript'),
    (4,'TypeScript'),
    (38,'Data Structures'),
    (41,'React'),
    (41,'Azure'),
    (6,'Node.js'),
    (44,'Django'),
    (11,'Python Programming'),
    (48,'Angular'),
    (36,'Java'),
    (43,'GraphQL'),
    (23,'Kubernetes'),
    (47,'Python Programming'),
    (3,'Java'),
    (48,'Algorithms'),
    (21,'Docker'),
    (47,'AWS'),
    (4,'React'),
    (33,'Flask'),
    (45,'REST APIs'),
    (18,'DevOps'),
    (32,'Testing'),
    (20,'.NET'),
    (34,'Algorithms'),
    (39,'Docker'),
    (41,'Java'),
    (16,'Python Programming'),
    (6,'React'),
    (7,'Algorithms'),
    (9,'Algorithms'),
    (21,'Web Security'),
    (29,'React'),
    (13,'Python Programming'),
    (16,'Docker'),
    (12,'Data Structures'),
    (44,'GraphQL'),
    (6,'Angular'),
    (4,'Flask'),
    (35,'Django'),
    (33,'System Design'),
    (41,'AWS'),
    (45,'JavaScript'),
    (51,'Docker'),
    (34,'Data Structures'),
    (32,'TypeScript'),
    (38,'Algorithms'),
    (4,'CI/CD'),
    (24,'Data Structures'),
    (24,'Flask'),
    (6,'Flask'),
    (43,'Flask'),
    (32,'Vue.js'),
    (30,'CI/CD'),
    (37,'HTML/CSS'),
    (10,'CI/CD'),
    (21,'Linux'),
    (9,'GraphQL'),
    (9,'Django'),
    (50,'Linux'),
    (15,'Node.js'),
    (47,'Docker'),
    (41,'C#'),
    (25,'Linux'),
    (17,'TypeScript'),
    (13,'AWS'),
    (17,'Algorithms'),
    (21,'Azure'),
    (51,'Vue.js'),
    (27,'GraphQL'),
    (42,'Data Structures'),
    (14,'Vue.js'),
    (48,'Flask'),
    (41,'DevOps'),
    (21,'MongoDB'),
    (3,'C#'),
    (20,'C#'),
    (36,'Testing'),
    (50,'AWS'),
    (30,'JavaScript'),
    (50,'React'),
    (17,'Azure'),
    (24,'Python Programming'),
    (3,'Linux'),
    (48,'REST APIs'),
    (4,'REST APIs'),
    (17,'React'),
    (44,'C#'),
    (22,'Data Structures'),
    (5,'Docker'),
    (33,'DevOps'),
    (28,'DevOps'),
    (20,'MongoDB'),
    (24,'React'),
    (12,'JavaScript'),
    (18,'Django'),
    (49,'Python Programming'),
    (47,'Data Structures'),
    (43,'DevOps'),
    (42,'React'),
    (22,'REST APIs'),
    (39,'React'),
    (44,'Linux'),
    (18,'JavaScript'),
    (7,'React'),
    (5,'React'),
    (33,'Data Structures'),
    (28,'MongoDB'),
    (44,'Git'),
    (41,'Flask'),
    (26,'C#'),
    (38,'Flask'),
    (37,'Vue.js'),
    (30,'HTML/CSS'),
    (23,'CI/CD'),
    (20,'SQL Database'),
    (43,'Data Structures'),
    (47,'HTML/CSS'),
    (7,'Angular'),
    (10,'Django'),
    (2,'Docker'),
    (9,'TypeScript'),
    (50,'HTML/CSS'),
    (46,'TypeScript'),
    (43,'Python Programming'),
    (46,'Data Structures'),
    (11,'SQL Database'),
    (14,'DevOps'),
    (18,'SQL Database'),
    (5,'Node.js'),
    (5,'TypeScript'),
    (34,'SQL Database'),
    (11,'HTML/CSS'),
    (6,'Python Programming'),
    (39,'JavaScript'),
    (45,'DevOps'),
    (13,'Django'),
    (36,'Angular'),
    (14,'MongoDB'),
    (35,'GraphQL'),
    (42,'Python Programming'),
    (10,'Angular'),
    (43,'JavaScript'),
    (37,'DevOps'),
    (31,'SQL Database'),
    (35,'C#'),
    (47,'Git'),
    (3,'Testing'),
    (45,'System Design'),
    (11,'Java'),
    (18,'HTML/CSS'),
    (24,'TypeScript'),
    (49,'GraphQL'),
    (27,'Web Security'),
    (11,'Kubernetes'),
    (22,'DevOps'),
    (24,'DevOps'),
    (11,'AWS'),
    (19,'GraphQL'),
    (42,'Kubernetes'),
    (24,'Docker'),
    (26,'AWS'),
    (31,'MongoDB'),
    (22,'GraphQL'),
    (30,'System Design'),
    (50,'Algorithms'),
    (11,'DevOps'),
    (13,'Node.js'),
    (39,'Kubernetes'),
    (40,'GraphQL'),
    (45,'Azure'),
    (37,'C#'),
    (20,'GraphQL'),
    (43,'HTML/CSS'),
    (12,'System Design'),
    (27,'Vue.js'),
    (26,'Kubernetes'),
    (48,'Azure'),
    (2,'SQL Database'),
    (5,'CI/CD'),
    (15,'Azure'),
    (25,'Angular'),
    (27,'Docker'),
    (6,'REST APIs'),
    (19,'AWS'),
    (51,'Git'),
    (17,'AWS'),
    (25,'Docker'),
    (10,'MongoDB'),
    (11,'Linux'),
    (20,'Angular'),
    (50,'Flask'),
    (7,'AWS'),
    (12,'TypeScript'),
    (50,'Web Security'),
    (15,'MongoDB'),
    (29,'AWS'),
    (50,'Vue.js'),
    (45,'AWS'),
    (32,'React'),
    (44,'DevOps'),
    (4,'Kubernetes'),
    (45,'MongoDB'),
    (33,'Docker'),
    (43,'Algorithms'),
    (8,'System Design'),
    (34,'System Design'),
    (45,'Node.js'),
    (49,'React'),
    (40,'JavaScript'),
    (35,'System Design'),
    (27,'System Design'),
    (38,'Azure'),
    (25,'REST APIs'),
    (30,'Web Security'),
    (7,'Azure'),
    (35,'Flask'),
    (18,'System Design'),
    (18,'Java'),
    (23,'REST APIs'),
    (36,'Vue.js'),
    (22,'Python Programming'),
    (4,'Testing'),
    (33,'TypeScript'),
    (34,'React'),
    (35,'.NET'),
    (5,'C#'),
    (41,'Docker'),
    (30,'GraphQL'),
    (31,'JavaScript'),
    (6,'TypeScript'),
    (15,'Algorithms'),
    (14,'Flask'),
    (36,'System Design'),
    (14,'Azure'),
    (4,'HTML/CSS'),
    (36,'Data Structures'),
    (43,'Git'),
    (31,'Node.js'),
    (19,'HTML/CSS'),
    (3,'Algorithms'),
    (36,'Docker'),
    (16,'REST APIs'),
    (27,'Node.js'),
    (50,'TypeScript'),
    (12,'Kubernetes'),
    (18,'GraphQL'),
    (6,'System Design'),
    (24,'.NET'),
    (22,'Java'),
    (51,'CI/CD'),
    (7,'Flask'),
    (16,'Testing'),
    (18,'MongoDB'),
    (33,'GraphQL'),
    (35,'Data Structures'),
    (23,'Git'),
    (32,'Linux'),
    (28,'Web Security'),
    (27,'AWS'),
    (18,'Algorithms'),
    (45,'Data Structures'),
    (20,'Vue.js'),
    (22,'HTML/CSS'),
    (17,'Flask'),
    (10,'Java'),
    (28,'Testing'),
    (15,'Kubernetes'),
    (15,'AWS'),
    (40,'REST APIs'),
    (31,'React'),
    (51,'Azure'),
    (19,'Kubernetes'),
    (12,'Vue.js'),
    (18,'Docker'),
    (33,'Algorithms'),
    (24,'C#'),
    (21,'Kubernetes'),
    (39,'AWS'),
    (32,'JavaScript'),
    (25,'CI/CD'),
    (49,'Flask'),
    (18,'Web Security'),
    (36,'Kubernetes'),
    (14,'Python Programming'),
    (27,'Django'),
    (44,'CI/CD'),
    (4,'JavaScript'),
    (18,'Angular'),
    (33,'Git'),
    (47,'Linux'),
    (50,'MongoDB'),
    (13,'Angular'),
    (34,'CI/CD'),
    (44,'Data Structures'),
    (9,'Azure'),
    (46,'Django'),
    (24,'Azure'),
    (10,'DevOps'),
    (30,'MongoDB'),
    (48,'Docker'),
    (28,'Python Programming'),
    (35,'DevOps'),
    (15,'Linux'),
    (8,'Linux'),
    (26,'Docker'),
    (20,'TypeScript'),
    (2,'Azure'),
    (47,'.NET'),
    (7,'.NET'),
    (33,'Azure'),
    (44,'Vue.js'),
    (42,'Azure'),
    (3,'JavaScript'),
    (41,'MongoDB'),
    (29,'Django'),
    (23,'Docker'),
    (47,'Java'),
    (45,'Linux'),
    (27,'HTML/CSS'),
    (16,'React'),
    (35,'Angular'),
    (17,'GraphQL'),
    (3,'Azure'),
    (37,'Java'),
    (2,'AWS'),
    (37,'Kubernetes'),
    (22,'Kubernetes'),
    (50,'SQL Database'),
    (11,'React'),
    (32,'Docker'),
    (14,'CI/CD'),
    (27,'Linux'),
    (26,'Data Structures'),
    (18,'TypeScript'),
    (10,'Algorithms'),
    (48,'Kubernetes'),
    (3,'Docker'),
    (24,'Web Security'),
    (44,'System Design'),
    (38,'C#'),
    (30,'Data Structures'),
    (38,'Vue.js'),
    (49,'System Design'),
    (17,'Django'),
    (38,'HTML/CSS'),
    (29,'Data Structures'),
    (25,'Algorithms'),
    (20,'Testing'),
    (38,'SQL Database'),
    (50,'JavaScript'),
    (9,'HTML/CSS'),
    (38,'Python Programming'),
    (5,'HTML/CSS'),
    (16,'Linux'),
    (45,'Vue.js'),
    (28,'JavaScript'),
    (23,'System Design'),
    (15,'SQL Database'),
    (15,'Testing'),
    (39,'Java'),
    (8,'Vue.js'),
    (8,'Data Structures'),
    (4,'AWS'),
    (37,'MongoDB'),
    (48,'Linux'),
    (12,'DevOps'),
    (44,'Flask'),
    (21,'Node.js'),
    (32,'Node.js'),
    (29,'Python Programming'),
    (49,'REST APIs'),
    (46,'Python Programming'),
    (21,'TypeScript'),
    (27,'JavaScript'),
    (9,'Node.js'),
    (7,'JavaScript'),
    (33,'HTML/CSS'),
    (7,'CI/CD'),
    (46,'SQL Database'),
    (15,'System Design'),
    (6,'Django'),
    (27,'Algorithms'),
    (23,'HTML/CSS'),
    (37,'AWS'),
    (16,'System Design'),
    (49,'DevOps'),
    (46,'Azure'),
    (40,'System Design'),
    (26,'System Design'),
    (25,'C#'),
    (36,'Git'),
    (24,'Algorithms'),
    (47,'Kubernetes'),
    (35,'AWS'),
    (45,'Testing'),
    (41,'JavaScript'),
    (42,'Git'),
    (47,'SQL Database'),
    (31,'Angular'),
    (11,'Docker'),
    (17,'Testing'),
    (7,'Data Structures'),
    (32,'SQL Database'),
    (20,'CI/CD'),
    (45,'Web Security'),
    (29,'C#'),
    (36,'C#'),
    (31,'AWS'),
    (47,'Node.js'),
    (6,'.NET'),
    (16,'GraphQL'),
    (24,'Angular'),
    (44,'Web Security'),
    (19,'Java'),
    (45,'Java'),
    (9,'Linux'),
    (24,'SQL Database'),
    (27,'Data Structures'),
    (6,'JavaScript'),
    (11,'JavaScript'),
    (45,'GraphQL'),
    (42,'DevOps'),
    (43,'.NET'),
    (50,'Python Programming'),
    (18,'Testing'),
    (6,'Git'),
    (25,'AWS'),
    (34,'GraphQL'),
    (23,'DevOps'),
    (50,'Django'),
    (11,'TypeScript'),
    (41,'Web Security'),
    (7,'C#'),
    (3,'CI/CD'),
    (17,'Java'),
    (35,'Vue.js'),
    (3,'React'),
    (36,'CI/CD'),
    (21,'Data Structures'),
    (10,'Testing'),
    (21,'C#'),
    (32,'CI/CD'),
    (12,'C#'),
    (5,'Flask'),
    (21,'HTML/CSS'),
    (30,'.NET'),
    (50,'Git'),
    (38,'GraphQL'),
    (10,'Kubernetes'),
    (35,'CI/CD'),
    (42,'AWS'),
    (19,'.NET'),
    (25,'DevOps'),
    (13,'.NET'),
    (16,'HTML/CSS'),
    (18,'Azure'),
    (40,'Data Structures'),
    (11,'Flask'),
    (5,'Algorithms'),
    (2,'Python Programming'),
    (29,'Azure'),
    (42,'JavaScript'),
    (32,'Azure'),
    (14,'REST APIs'),
    (10,'JavaScript'),
    (15,'JavaScript'),
    (5,'MongoDB'),
    (4,'Azure'),
    (17,'Node.js'),
    (45,'React'),
    (3,'MongoDB'),
    (41,'Django'),
    (51,'Algorithms'),
    (7,'Linux'),
    (27,'Python Programming'),
    (27,'SQL Database'),
    (41,'Testing'),
    (14,'AWS'),
    (46,'.NET'),
    (41,'Algorithms'),
    (10,'AWS'),
    (28,'React'),
    (37,'Django'),
    (12,'Node.js'),
    (39,'HTML/CSS'),
    (22,'CI/CD'),
    (26,'MongoDB'),
    (23,'Django'),
    (40,'AWS'),
    (3,'Django'),
    (36,'Flask'),
    (44,'Docker'),
    (13,'React'),
    (20,'JavaScript'),
    (18,'Flask'),
    (34,'Git'),
    (43,'Web Security'),
    (45,'Flask'),
    (16,'Django'),
    (50,'C#'),
    (33,'Python Programming'),
    (30,'Linux'),
    (44,'HTML/CSS'),
    (22,'Git'),
    (27,'REST APIs'),
    (6,'MongoDB'),
    (43,'CI/CD'),
    (39,'Linux'),
    (18,'CI/CD'),
    (41,'Linux'),
    (32,'HTML/CSS'),
    (9,'Data Structures'),
    (27,'Kubernetes'),
    (45,'Algorithms'),
    (31,'Azure'),
    (2,'.NET'),
    (6,'Data Structures'),
    (2,'TypeScript'),
    (5,'SQL Database'),
    (36,'Linux'),
    (48,'React'),
    (20,'Java'),
    (41,'REST APIs'),
    (13,'Docker'),
    (20,'Django'),
    (36,'Web Security'),
    (15,'Angular'),
    (37,'Docker'),
    (48,'Node.js'),
    (12,'.NET'),
    (26,'Angular'),
    (27,'.NET'),
    (21,'SQL Database'),
    (7,'GraphQL'),
    (15,'.NET'),
    (27,'DevOps'),
    (25,'Java'),
    (21,'Git'),
    (11,'CI/CD'),
    (38,'Testing'),
    (22,'Docker'),
    (23,'Angular'),
    (2,'Linux'),
    (37,'System Design'),
    (47,'MongoDB'),
    (34,'Web Security'),
    (4,'Data Structures'),
    (15,'Vue.js'),
    (48,'Django'),
    (25,'Vue.js'),
    (40,'Kubernetes'),
    (32,'.NET'),
    (18,'C#'),
    (34,'AWS'),
    (34,'Vue.js'),
    (19,'System Design'),
    (28,'Node.js'),
    (18,'REST APIs'),
    (28,'C#'),
    (35,'Algorithms'),
    (44,'Angular'),
    (38,'MongoDB'),
    (28,'TypeScript'),
    (17,'.NET'),
    (22,'Azure'),
    (41,'GraphQL'),
    (47,'Django'),
    (18,'Python Programming'),
    (12,'Python Programming'),
    (37,'REST APIs'),
    (37,'Angular'),
    (35,'Docker'),
    (51,'Web Security'),
    (5,'.NET'),
    (4,'Linux'),
    (32,'C#'),
    (50,'DevOps'),
    (47,'Azure'),
    (18,'Data Structures'),
    (42,'Algorithms'),
    (42,'Linux'),
    (41,'SQL Database'),
    (21,'Flask'),
    (17,'Docker'),
    (21,'Python Programming'),
    (4,'Web Security'),
    (13,'DevOps'),
    (49,'Vue.js'),
    (8,'GraphQL'),
    (28,'Vue.js'),
    (41,'Kubernetes'),
    (5,'Django'),
    (37,'Git'),
    (12,'Angular'),
    (50,'.NET'),
    (8,'Azure'),
    (5,'JavaScript'),
    (12,'Algorithms'),
    (21,'GraphQL'),
    (51,'Angular'),
    (16,'Java'),
    (34,'Linux'),
    (27,'Flask'),
    (6,'AWS'),
    (18,'Node.js'),
    (25,'Python Programming'),
    (50,'System Design'),
    (13,'MongoDB'),
    (51,'.NET'),
    (47,'DevOps'),
    (39,'Testing'),
    (16,'MongoDB'),
    (21,'DevOps'),
    (23,'Web Security'),
    (8,'Django'),
    (30,'Git'),
    (12,'HTML/CSS'),
    (20,'Node.js'),
    (9,'Docker'),
    (36,'Algorithms'),
    (33,'Vue.js'),
    (29,'Algorithms'),
    (32,'GraphQL'),
    (13,'Java'),
    (42,'C#'),
    (37,'Web Security'),
    (23,'Node.js'),
    (6,'Kubernetes'),
    (47,'C#'),
    (23,'Vue.js'),
    (12,'Linux'),
    (5,'AWS'),
    (38,'TypeScript'),
    (34,'Node.js'),
    (45,'Docker'),
    (34,'REST APIs'),
    (8,'AWS'),
    (48,'System Design'),
    (47,'Testing'),
    (22,'Node.js'),
    (14,'System Design'),
    (22,'Testing'),
    (29,'SQL Database'),
    (4,'MongoDB'),
    (7,'Django'),
    (19,'React'),
    (8,'Git'),
    (21,'React'),
    (38,'System Design'),
    (2,'Vue.js'),
    (16,'AWS'),
    (50,'Angular'),
    (44,'.NET'),
    (43,'C#'),
    (45,'Git'),
    (35,'REST APIs'),
    (41,'Python Programming'),
    (18,'Linux'),
    (22,'System Design'),
    (47,'System Design'),
    (45,'Angular'),
    (5,'Git'),
    (21,'Angular'),
    (39,'Django'),
    (24,'GraphQL'),
    (20,'Linux'),
    (46,'Web Security'),
    (30,'React'),
    (43,'TypeScript'),
    (35,'Azure'),
    (37,'.NET'),
    (48,'Data Structures'),
    (15,'HTML/CSS'),
    (20,'Flask'),
    (4,'GraphQL'),
    (50,'Data Structures'),
    (51,'Kubernetes'),
    (50,'Node.js'),
    (3,'Data Structures'),
    (34,'DevOps'),
    (5,'Linux'),
    (37,'CI/CD'),
    (46,'Vue.js'),
    (29,'Linux'),
    (11,'Azure'),
    (10,'Azure'),
    (13,'Linux'),
    (33,'Linux'),
    (8,'REST APIs'),
    (10,'Flask'),
    (45,'Python Programming'),
    (15,'GraphQL'),
    (27,'C#'),
    (34,'Docker'),
    (26,'Azure'),
    (37,'Testing'),
    (26,'SQL Database'),
    (48,'Web Security'),
    (29,'Flask'),
    (2,'REST APIs'),
    (12,'Azure'),
    (24,'REST APIs'),
    (9,'Angular'),
    (3,'Angular'),
    (20,'DevOps'),
    (9,'Flask'),
    (13,'JavaScript'),
    (50,'Testing'),
    (22,'Algorithms'),
    (19,'Linux'),
    (10,'Node.js'),
    (48,'Java'),
    (31,'CI/CD'),
    (8,'Flask'),
    (10,'Git'),
    (51,'React'),
    (46,'Testing'),
    (16,'Azure'),
    (11,'GraphQL'),
    (24,'Linux'),
    (15,'Python Programming'),
    (21,'System Design'),
    (29,'Web Security'),
    (8,'Testing'),
    (42,'Java'),
    (35,'SQL Database'),
    (38,'JavaScript'),
    (38,'Java'),
    (15,'CI/CD'),
    (38,'Kubernetes'),
    (45,'TypeScript'),
    (10,'System Design'),
    (39,'Azure')
) AS cs([course_id], [skill_name])
INNER JOIN [dbo].[Skill] s ON cs.[skill_name] = s.[SkillName]
WHERE NOT EXISTS (
    -- Avoid duplicate inserts
    SELECT 1 FROM [dbo].[CourseSkill]
    WHERE [CourseId] = cs.[course_id] AND [SkillId] = s.[SkillId]
);

-- ============================================================================
-- VERIFICATION
-- ============================================================================

SELECT
    COUNT(*) as [Total CourseSkills Inserted],
    COUNT(DISTINCT [CourseId]) as [Unique Courses],
    COUNT(DISTINCT [SkillId]) as [Unique Skills]
FROM [dbo].[CourseSkill];

-- Sample: Show skills for Course 2
SELECT TOP 10
    cs.[CourseSkillId],
    c.[Title] as [CourseName],
    s.[SkillName],
    s.[Category],
    cs.[ProficiencyLevel]
FROM [dbo].[CourseSkill] cs
INNER JOIN [dbo].[Course] c ON cs.[CourseId] = c.[CourseId]
INNER JOIN [dbo].[Skill] s ON cs.[SkillId] = s.[SkillId]
WHERE cs.[CourseId] = 2
ORDER BY s.[SkillName];

-- Count by course
SELECT TOP 10
    c.[CourseId],
    c.[Title],
    COUNT(cs.[SkillId]) as [SkillCount]
FROM [dbo].[Course] c
LEFT JOIN [dbo].[CourseSkill] cs ON c.[CourseId] = cs.[CourseId]
WHERE c.[CourseId] BETWEEN 2 AND 51
GROUP BY c.[CourseId], c.[Title]
ORDER BY [SkillCount] DESC, c.[CourseId];
